
server:
  port: 8000
    
# Oracle #
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:free
    username: CASOLP
    password: 123456
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
